### ISSUE TITLE
Creating 1 directories

### ISSUE THREAD

**Issue by battis** [battis/bootstrapsmarty#3]
Not quite sure where this bug is -- could be in a number of projects, but this is the one that threw the original exception:

> [Mon Apr 04 08:27:59.141285 2016] [:error] [pid 32124] [client 104.129.82.2:51977] PHP Fatal error:  Uncaught exception 'Battis\BootstrapSmarty\BootstrapSmarty_Exception' with message 'The directory '/var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/hacks/templates/1/' was created (should have already existed and been populated)' in /var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/vendor/battis/bootstrapsmarty/src/BootstrapSmarty.php:156\nStack trace:\n#0 /var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/vendor/battis/bootstrapsmarty/src/BootstrapSmarty.php(270): Battis\BootstrapSmarty\BootstrapSmarty::testReadableDirectory('/var/www/skunkw...')\n#1 /var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/vendor/smtech/stmarkssmarty/src/StMarksSmarty.php(28): Battis\BootstrapSmarty\BootstrapSmarty->__construct(true, '/var/www/skunkw...', NULL, NULL)\n#2 /var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/vendor/smtech/stmarkssmarty/src/StMarksSmarty.php(22): smtech\StMarksSmarty\StMarksSmarty->__construct(true, '/var/www/skunkw...', NULL, NULL)\n#3 /var/www/skunkworks.stm in /var/www/skunkworks.stmarksschool.org/canvas/lti/canvashack/vendor/battis/bootstrapsmarty/src/BootstrapSmarty.php on line 156, referer: https://stmarksschool.instructure.com/courses/97

This occurred on a fresh load of Composer packages to the server, happened the first time each directory was accessed, but not again afterwards, and the 1 directories were, indeed, created.

**Comment by battis** [comment]
No. Wait. I know what it is. It's [this](https://github.com/smtech/canvashack/blob/develop/common.inc.php#L125), which is no longer correct.
